### ISSUE TITLE
atom collision slider snap is not working

### ISSUE THREAD

**Issue by bardella** [gvcm/CWAPP#165]
collision slider snap are not working. it should be turned on when both LOCK and DNO are OFF

**Comment by ThanosSar** [comment]
As I have explained, this cannot work because the user might create a cell where there are many collisions and then go to change the scales, angles or even the motif. How will then the collisions be detected and provide us the snap values (for scales/angles sliders) while there are also many collisions there?

It is not a simple problem, it might have a solution (it also might not) but it needs good thinking to invent a process to do all that and make it work right and without any bugs.

**Comment by bardella** [comment]
... seems this still needs adjustments; I'm having issues with snap with different variations of autopilot locker status

**Comment by bardella** [comment]
particularly at the vectorial mode this is not working...

**Comment by bardella** [comment]
with previous one, no need of this
