### ISSUE TITLE
main menu adjustments

### ISSUE THREAD

**Issue by bardella** [gvcm/CWAPP#212]
adjustments are required for the main application menu:

- [x] " shorten" a bit the width of the bar (as in 1)
- [x] eliminate the space between the menu and the end of the screen (as in 2)
- [x] ensure menu goes until the end of the screen (as in 3)
- [x] optimize menu for opening in phones. maybe "auto"  resizing of the menu is a viable solution

image below

![image](https://cloud.githubusercontent.com/assets/4349542/14510205/ae012da2-01a6-11e6-8841-27113be0ba17.png)

**Comment by ekaratzaferis** [comment]
(3) The menu does expand to the end of the screen. I've tested it with a bunch of different resolutions in Google Chrome Debugger. What is the resolution of the screen you're using?

(2) This has to do with the scrollbar pluging we're using. It's occupying the space you're showing. In this case, there's no scrollable area, that's why it's showing this empty space.

(4) The menu zoom feature resizes the menu to 70% if needed, but we'll need to make heavy HTML & CSS changes to the UI in order to make menu work in a new fashion for mobile devices.

(1) I've "trimmed" the width of the menu ribbon.
