### ISSUE TITLE
mobile menu fixes

### ISSUE THREAD

**Issue by bardella** [gvcm/CWAPP#281]
mobile menu needs 2 fixes:

1. for some reason menu is getting cut on certain phones... (all iphones affected) see below
![image](https://cloud.githubusercontent.com/assets/4349542/22849263/b0260aaa-efe2-11e6-9c86-3de48b342a87.png)

2. after selecting the lattice and adding an atom, menu gets shifted and top buttons functionalities can no longer be accessed. this fix is more urgent

![image](https://cloud.githubusercontent.com/assets/4349542/22849325/78605278-efe3-11e6-89b1-a67a638442c2.png)

**Comment by ekaratzaferis** [comment]
Latest Changes:

- Replaced the scrollbar with a new one

- Got rid of some constants values that were used to manage the menu functionality and the overall resizing process of the page

- Menu zoom in/out works fine, both on desktop and on mobile

- User "pinch" zoom is disabled in the mobile because it creates a very weird behavior. User was able to "completely" zoom out and force Chrome to fit all of the page in the mobile screen. When this happens and the open/close menu button is pressed, additionally to our code that shifts the menu in the non visible part of the screen in order to hide it, the Chrome also zooms out to fit the whole page. As a result when the menu is closed, it's shifted right and the Chrome zooms out (still visible) and when the menu is open, it's shifted left and Chrome zooms in (back to normal)

Th
